Public Class FormListCustomer
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        MstCustomerTableAdapter1.Fill(DataSetCustomer1.mstCustomer)
    End Sub
End Class